---
- name: dev
  cidr: 100.96.0.0/15
  region: us-east-2
  azs:
    - a
    - b
  subnet_bits: 20
  subnets:
    private: 2
    lambda: 2
    database: 2
- name: sit
  cidr: 100.98.0.0/15
  region: us-east-2
  azs:
    - a
    - b
  subnets:
    private: 2
    lambda: 2
    database: 2
- name: pre
  cidr: 100.100.0.0/15
  region: us-east-2
  azs:
    - a
    - b
  subnets:
    private: 2
    lambda: 2
    database: 2
- name: prod
  cidr: 100.102.0.0/15
  region: us-east-2
  azs:
    - a
    - b
  subnets:
    private: 2
    lambda: 2
    database: 2
- name: sharedtools
  cidr: 100.103.0.0/16
  region: us-east-2
  azs:
    - a
    - b
  subnets:
    private: 2
    lambda: 2
    database: 2