---
dev:
  cidr: 100.96.0.0/15
  region: us-east-2
  azs:
    - us-east-2a
    - us-east-2b
  subnets:
    private:
      us-east-2a: 100.96.0.0/18
      us-east-2b: 100.96.64.0/18
    lambda:
      us-east-2a: 100.96.128.0/18
      us-east-2b: 100.96.192.0/18
    database:
      us-east-2a: 100.97.0.0/18
      us-east-2b: 100.97.64.0/18
  azs_region_length: 2
  total_subnets: 6
sit:
  cidr: 100.98.0.0/15
  region: us-east-2
  azs:
    - us-east-2a
    - us-east-2b
  subnets:
    private:
      us-east-2a: 100.98.0.0/18
      us-east-2b: 100.98.64.0/18
    lambda:
      us-east-2a: 100.98.128.0/18
      us-east-2b: 100.98.192.0/18
    database:
      us-east-2a: 100.99.0.0/18
      us-east-2b: 100.99.64.0/18
  azs_region_length: 2
  total_subnets: 6
pre:
  cidr: 100.100.0.0/15
  region: us-east-2
  azs:
    - us-east-2a
    - us-east-2b
  subnets:
    private:
      us-east-2a: 100.100.0.0/18
      us-east-2b: 100.100.64.0/18
    lambda:
      us-east-2a: 100.100.128.0/18
      us-east-2b: 100.100.192.0/18
    database:
      us-east-2a: 100.101.0.0/18
      us-east-2b: 100.101.64.0/18
  azs_region_length: 2
  total_subnets: 6
prod:
  cidr: 100.102.0.0/15
  region: us-east-2
  azs:
    - us-east-2a
    - us-east-2b
  subnets:
    private:
      us-east-2a: 100.102.0.0/18
      us-east-2b: 100.102.64.0/18
    lambda:
      us-east-2a: 100.102.128.0/18
      us-east-2b: 100.102.192.0/18
    database:
      us-east-2a: 100.103.0.0/18
      us-east-2b: 100.103.64.0/18
  azs_region_length: 2
  total_subnets: 6
sharedtools:
  cidr: 100.103.0.0/16
  region: us-east-2
  azs:
    - us-east-2a
    - us-east-2b
  subnets:
    private:
      us-east-2a: 100.103.0.0/19
      us-east-2b: 100.103.32.0/19
    lambda:
      us-east-2a: 100.103.64.0/19
      us-east-2b: 100.103.96.0/19
    database:
      us-east-2a: 100.103.128.0/19
      us-east-2b: 100.103.160.0/19
  azs_region_length: 2
  total_subnets: 6
