---
sharedtools:
  cidr: 100.100.0.0/16
  region: us-east-2
  azs:
    - us-east-2a
    - us-east-2b
  subnets:
    private:
      us-east-2a: 100.100.0.0/19
      us-east-2b: 100.100.32.0/19
    lambda:
      us-east-2a: 100.100.64.0/19
      us-east-2b: 100.100.96.0/19
    database:
      us-east-2a: 100.100.128.0/19
      us-east-2b: 100.100.160.0/19
  azs_region_length: 2
  total_subnets: 6
nickel:
  cidr: 100.101.0.0/16
  region: us-east-1
  azs:
    - us-east-1a
    - us-east-1b
  subnets:
    private:
      us-east-1a: 100.101.0.0/18
      us-east-1b: 100.101.64.0/18
    lambda:
      us-east-1a: 100.101.128.0/18
      us-east-1b: 100.101.192.0/18
  azs_region_length: 2
  total_subnets: 4
sandbox:
  cidr: 100.102.0.0/16
  region: us-east-2
  azs:
    - us-east-2a
    - us-east-2b
  subnets:
    private:
      us-east-2a: 100.102.0.0/19
      us-east-2b: 100.102.32.0/19
    lambda:
      us-east-2a: 100.102.64.0/19
      us-east-2b: 100.102.96.0/19
    database:
      us-east-2a: 100.102.128.0/19
      us-east-2b: 100.102.160.0/19
  azs_region_length: 2
  total_subnets: 6
dev:
  cidr: 100.103.0.0/16
  region: us-east-2
  azs:
    - us-east-2a
    - us-east-2b
  subnets:
    private:
      us-east-2a: 100.103.0.0/19
      us-east-2b: 100.103.32.0/19
    lambda:
      us-east-2a: 100.103.64.0/19
      us-east-2b: 100.103.96.0/19
    database:
      us-east-2a: 100.103.128.0/19
      us-east-2b: 100.103.160.0/19
  azs_region_length: 2
  total_subnets: 6
sit:
  cidr: 100.104.0.0/16
  region: us-east-2
  azs:
    - us-east-2a
    - us-east-2b
  subnets:
    private:
      us-east-2a: 100.104.0.0/19
      us-east-2b: 100.104.32.0/19
    lambda:
      us-east-2a: 100.104.64.0/19
      us-east-2b: 100.104.96.0/19
    database:
      us-east-2a: 100.104.128.0/19
      us-east-2b: 100.104.160.0/19
  azs_region_length: 2
  total_subnets: 6
perf:
  cidr: 100.105.0.0/16
  region: us-east-2
  azs:
    - us-east-2a
    - us-east-2b
  subnets:
    private:
      us-east-2a: 100.105.0.0/19
      us-east-2b: 100.105.32.0/19
    lambda:
      us-east-2a: 100.105.64.0/19
      us-east-2b: 100.105.96.0/19
    database:
      us-east-2a: 100.105.128.0/19
      us-east-2b: 100.105.160.0/19
  azs_region_length: 2
  total_subnets: 6
pre:
  cidr: 100.106.0.0/16
  region: us-east-2
  azs:
    - us-east-2a
    - us-east-2b
  subnets:
    private:
      us-east-2a: 100.106.0.0/19
      us-east-2b: 100.106.32.0/19
    lambda:
      us-east-2a: 100.106.64.0/19
      us-east-2b: 100.106.96.0/19
    database:
      us-east-2a: 100.106.128.0/19
      us-east-2b: 100.106.160.0/19
  azs_region_length: 2
  total_subnets: 6
prod:
  cidr: 100.107.0.0/16
  region: us-east-2
  azs:
    - us-east-2a
    - us-east-2b
  subnets:
    private:
      us-east-2a: 100.107.0.0/19
      us-east-2b: 100.107.32.0/19
    lambda:
      us-east-2a: 100.107.64.0/19
      us-east-2b: 100.107.96.0/19
    database:
      us-east-2a: 100.107.128.0/19
      us-east-2b: 100.107.160.0/19
  azs_region_length: 2
  total_subnets: 6
